version: '3.9'

services:
  api:
    container_name: todoapp-api
    build:
      context: ./
      dockerfile: Dockerfile 
    ports:
      - "8082:8080"
    environment:
      - DB_HOSTNAME=db
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  db:
    container_name: todoapp-database
    image: mysql:8
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql-storage:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}

volumes:
  mysql-storage: